module View.Keyboard exposing (keyboard) -- where

import Html exposing (..)
import Html.Events exposing (onClick)
import Html.Attributes exposing (class, value)

import Update exposing (..)
import Msg exposing (..)

keyboard : Html Msg
keyboard =
  let
    keys = 
      [ li [ class "key lower c"  , value "0"  ] []
      , li [ class "key higher cs", value "1"  ] []
      , li [ class "key lower d"  , value "2"  ] []
      , li [ class "key higher ds", value "3"  ] []
      , li [ class "key lower e"  , value "4"  ] []
      , li [ class "key lower f"  , value "5"  ] []
      , li [ class "key higher fs", value "6"  ] []
      , li [ class "key lower g"  , value "7"  ] []
      , li [ class "key higher gs", value "8"  ] []
      , li [ class "key lower a"  , value "9"  ] []
      , li [ class "key higher as", value "10" ] []
      , li [ class "key lower b"  , value "11" ] []
      , li [ class "key lower c"  , value "12" ] []
      , li [ class "key higher cs", value "13" ] []
      , li [ class "key lower d"  , value "14" ] []
      , li [ class "key higher ds", value "15" ] []
      , li [ class "key lower e"  , value "16" ] []
      , li [ class "key lower f"  , value "17" ] []
      , li [ class "key higher fs", value "18" ] []
      , li [ class "key lower g"  , value "19" ] []
      , li [ class "key higher gs", value "20" ] []
      , li [ class "key lower a"  , value "21" ] []
      , li [ class "key higher as", value "22" ] []
      , li [ class "key lower b"  , value "23" ] []
      , li [ class "key lower c"  , value "24" ] []
      , li [ class "key higher cs", value "25" ] []
      , li [ class "key lower d"  , value "26" ] []
      , li [ class "key higher ds", value "27" ] []
      , li [ class "key lower e"  , value "28" ] []
      , li [ class "key lower f"  , value "29" ] []
      , li [ class "key higher fs", value "30" ] []
      , li [ class "key lower g"  , value "31" ] []
      , li [ class "key higher gs", value "32" ] []
      , li [ class "key lower a"  , value "33" ] []
      , li [ class "key higher as", value "34" ] []
      , li [ class "key lower b"  , value "35" ] []
      , li [ class "key lower c"  , value "36" ] []
      , li [ class "key higher cs", value "37" ] []
      , li [ class "key lower d"  , value "38" ] []
      , li [ class "key higher ds", value "39" ] []
      , li [ class "key lower e"  , value "40" ] []
      , li [ class "key lower f"  , value "41" ] []
      , li [ class "key higher fs", value "42" ] []
      , li [ class "key lower g"  , value "43" ] []
      , li [ class "key higher gs", value "44" ] []
      , li [ class "key lower a"  , value "45" ] []
      , li [ class "key higher as", value "46" ] []
      , li [ class "key lower b"  , value "47" ] []
      , li [ class "key lower c"  , value "48" ] []
      , li [ class "key higher cs", value "49" ] []
      , li [ class "key lower d"  , value "50" ] []
      , li [ class "key higher ds", value "51" ] []
      , li [ class "key lower e"  , value "52" ] []
      , li [ class "key lower f"  , value "53" ] []
      , li [ class "key higher fs", value "54" ] []
      , li [ class "key lower g"  , value "55" ] []
      , li [ class "key higher gs", value "56" ] []
      , li [ class "key lower a"  , value "57" ] []
      , li [ class "key higher as", value "58" ] []
      , li [ class "key lower b"  , value "59" ] []
      , li [ class "key lower c c3", value "60" ] []
      , li [ class "key higher cs", value "61" ] []
      , li [ class "key lower d"  , value "62" ] []
      , li [ class "key higher ds", value "63" ] []
      , li [ class "key lower e"  , value "64" ] []
      , li [ class "key lower f"  , value "65" ] []
      , li [ class "key higher fs", value "66" ] []
      , li [ class "key lower g"  , value "67" ] []
      , li [ class "key higher gs", value "68" ] []
      , li [ class "key lower a"  , value "69" ] []
      , li [ class "key higher as", value "70" ] []
      , li [ class "key lower b"  , value "71" ] []
      , li [ class "key lower c"  , value "72" ] []
      , li [ class "key higher cs", value "73" ] []
      , li [ class "key lower d"  , value "74" ] []
      , li [ class "key higher ds", value "75" ] []
      , li [ class "key lower e"  , value "76" ] []
      , li [ class "key lower f"  , value "77" ] []
      , li [ class "key higher fs", value "78" ] []
      , li [ class "key lower g"  , value "79" ] []
      , li [ class "key higher gs", value "80" ] []
      , li [ class "key lower a"  , value "81" ] []
      , li [ class "key higher as", value "82" ] []
      , li [ class "key lower b"  , value "83" ] []
      , li [ class "key lower c"  , value "84" ] []
      , li [ class "key higher cs", value "85" ] []
      , li [ class "key lower d"  , value "86" ] []
      , li [ class "key higher ds", value "87" ] []
      , li [ class "key lower e"  , value "88" ] []
      , li [ class "key lower f"  , value "89" ] []
      , li [ class "key higher fs", value "90" ] []
      , li [ class "key lower g"  , value "91" ] []
      , li [ class "key higher gs", value "92" ] []
      , li [ class "key lower a"  , value "93" ] []
      , li [ class "key higher as", value "94" ] []
      , li [ class "key lower b"  , value "95" ] []
      , li [ class "key lower c"  , value "96" ] []
      , li [ class "key higher cs", value "97" ] []
      , li [ class "key lower d"  , value "98" ] []
      , li [ class "key higher ds", value "99" ] []
      , li [ class "key lower e"  , value "100"] []
      , li [ class "key lower f"  , value "101"] []
      , li [ class "key higher fs", value "102"] []
      , li [ class "key lower g"  , value "103"] []
      , li [ class "key higher gs", value "104"] []
      , li [ class "key lower a"  , value "105"] []
      , li [ class "key higher as", value "106"] []
      , li [ class "key lower b"  , value "107"] []
      , li [ class "key lower c"  , value "108"] []
      , li [ class "key higher cs", value "109"] []
      , li [ class "key lower d"  , value "110"] []
      , li [ class "key higher ds", value "111"] []
      , li [ class "key lower e"  , value "112"] []
      , li [ class "key lower f"  , value "113"] []
      , li [ class "key higher fs", value "114"] []
      , li [ class "key lower g"  , value "115"] []
      , li [ class "key higher gs", value "116"] []
      , li [ class "key lower a"  , value "117"] []
      , li [ class "key higher as", value "118"] []
      , li [ class "key lower b"  , value "119"] []
      , li [ class "key lower c"  , value "120"] []
      , li [ class "key higher cs", value "121"] []
      , li [ class "key lower d"  , value "122"] []
      , li [ class "key higher ds", value "123"] []
      , li [ class "key lower e"  , value "124"] []
      , li [ class "key lower f"  , value "125"] []
      , li [ class "key higher fs", value "126"] []
      , li [ class "key lower g"  , value "127"] []
      ]
  in
    ul [ class "keyboard" ] keys

