module Container.Panel.View.Instructions exposing (..)

-- where

import Html exposing (..)
import Html.Attributes exposing (..)


instructions : Html a
instructions =
    div [ class "pannel-instructions" ]
        [ span [ class "instructions__title" ] [ text "INSTRUCTIONS" ]
        , table [ class "instructions" ]
            [ tr [ class "instructions__entry" ]
                [ td [] [ text "Z" ]
                , td [ class "instructions__label" ] [ text "play C" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "X" ]
                , td [ class "instructions__label" ] [ text "octave down" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "C" ]
                , td [ class "instructions__label" ] [ text "velocity up" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "V" ]
                , td [ class "instructions__label" ] [ text "velocity down" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "A" ]
                , td [ class "instructions__label" ] [ text "play C" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "W" ]
                , td [ class "instructions__label" ] [ text "play C#" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "S" ]
                , td [ class "instructions__label" ] [ text "play D" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "E" ]
                , td [ class "instructions__label" ] [ text "play D#" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "D" ]
                , td [ class "instructions__label" ] [ text "play E" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "F" ]
                , td [ class "instructions__label" ] [ text "play F" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "T" ]
                , td [ class "instructions__label" ] [ text "play F#" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "G" ]
                , td [ class "instructions__label" ] [ text "play G" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "Y" ]
                , td [ class "instructions__label" ] [ text "play G#" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "H" ]
                , td [ class "instructions__label" ] [ text "play A" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "U" ]
                , td [ class "instructions__label" ] [ text "play A#" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "P" ]
                , td [ class "instructions__label" ] [ text "play B" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "J" ]
                , td [ class "instructions__label" ] [ text "play C 8va" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "K" ]
                , td [ class "instructions__label" ] [ text "play C# 8va" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "O" ]
                , td [ class "instructions__label" ] [ text "play D 8va" ]
                ]
            , tr [ class "instructions__entry" ]
                [ td [] [ text "L" ]
                , td [ class "instructions__label" ] [ text "play D# 8va" ]
                ]
            ]
        ]
